version: '3.1'
services:
  app:
    image: iamusayev/1990
    restart: always
    ports:
      - 8089:8086
    depends_on:
      - db
    environment:
      DB_CONNECTION_IP: db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5438:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
